name: Bug Report
description: 'When submitting an issue enable LOG_LEVEL="trace" and have a look at the docs.'
labels: ['bug ðŸ›']
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an open or closed issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing open and closed issues and I checked the docs https://jokob-sk.github.io/NetAlertX/
      required: true
- type: checkboxes
  attributes:
    label: The issue occurs in the following browsers. Select at least 2.
    description: This step helps me understand if this is a cache or browser-specific issue. 
    options:
    - label: "Firefox"
    - label: "Chrome"
    - label: "Edge"
    - label: "Safari (unsupported) - PRs welcome"
    - label: "N/A - This is an issue with the backend"
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. With these settings...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: app.conf
    description: |
      Paste relevant `app.conf`settings (remove sensitive info)    
    render: python
  validations:
    required: false
- type: textarea
  attributes:
    label: docker-compose.yml
    description: |
      Paste your `docker-compose.yml`    
    render: python
  validations:
    required: false
- type: dropdown
  id: installation_type
  attributes:
    label: What installation are you running?
    options:
      - Production (netalertx)
      - Dev (netalertx-dev)
      - Home Assistant (addon)
      - Home Assistant fa (full-access addon)
      - Bare-metal (community only support - Check Discord)
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Debug or Trace enabled
    description: I confirm I set `LOG_LEVEL` to `debug` or `trace`
    options:
    - label: I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.
      required: true
- type: textarea
  attributes:
    label: app.log
    description: |
      Logs with debug enabled (https://github.com/jokob-sk/NetAlertX/blob/main/docs/DEBUG_TIPS.md) âš 
      ***Generally speaking, all bug reports should have logs provided.***
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      Additionally, any additional info? Screenshots? References? Anything that will give us more context about the issue you are encountering!
      You can use `tail -100 /app/log/app.log` in the container if you have trouble getting to the log files or send them to netalertx@gmail.com with the issue number.
  validations:
    required: false
- type: textarea
  attributes:
    label: Docker Logs
    description: |
     You can retrieve the logs from Portainer -> Containers -> your NetAlertX container -> Logs or by running `sudo docker logs netalertx`.
  validations:
    required: true

