name: 🔐 Security Report
description: Report a security vulnerability or concern privately.
labels: ['security 🔐']
body:
- type: markdown
  attributes:
    value: |
      <!-- NETALERTX_TEMPLATE -->
- type: markdown
  attributes:
    value: |
      **Important:** For security reasons, please do **not** post sensitive security issues publicly in the issue tracker.
      Instead, send details to our security contact email: [jokob@duck.com](mailto:jokob@duck.com).

      We appreciate your responsible disclosure.
- type: textarea
  attributes:
    label: Brief summary (non-sensitive)
    description: Provide a non-sensitive overview of the security issue.
    required: true
- type: textarea
  attributes:
    label: Additional context or references
    description: Any other information or related reports.
    required: false
- type: checkboxes
  attributes:
    label: Have you sent this report via email to the security contact?
    options:
      - label: Yes, I have sent the details to jokob@duck.com
        required: true
      - label: Not yet, I will send it after opening this issue
