{
 "title": "NetAlertX Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Total Devices",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "netalertx_connected_devices + netalertx_offline_devices"
    }
   ]
  },
  {
   "title": "Connected",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "netalertx_connected_devices" }
   ]
  },
  {
   "title": "Favorites",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "netalertx_favorite_devices" }
   ]
  },
  {
   "title": "New Devices",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "netalertx_new_devices" }
   ]
  },
  {
   "title": "Down",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "netalertx_down_devices" }
   ]
  },
  {
   "title": "Archived",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "netalertx_archived_devices" }
   ]
  },
  {
   "title": "Device Presence",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "netalertx_connected_devices", "legendFormat": "Connected" },
    {
     "expr": "netalertx_total_devices - (netalertx_connected_devices + netalertx_down_devices)",
     "legendFormat": "Offline"
    },
    { "expr": "netalertx_down_devices", "legendFormat": "Down Devices" }
   ]
  },
  {
   "title": "Connected Devices",
   "type": "table",
   "description": "Connected (Online) Devices",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "netalertx_device_status{device_status=\"Online\"}"
    }
   ]
  },
  {
   "title": "Disconnected Devices",
   "type": "table",
   "description": "Disconnected(Offline) Devices",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "netalertx_device_status{device_status=\"Offline\"}"
    }
   ]
  }
 ]
}